test_that("modelSizes builds correct mSize objects (1)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-6
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  mSizes<-modelSizes(Post)
  expect_equal(class(mSizes[[1]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[2]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[3]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[4]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[5]]),c("gg", "ggplot","ggarrange"))
  dev.off()
})

test_that("modelSizes builds correct mSize objects (2)", {
  x1<-rnorm(50, mean = 0, sd = 5)
  x2<-rnorm(50, mean = 0, sd = 2)
  x3<-rnorm(50, mean = 0, sd = 7)
  x4<-rnorm(50, mean = 0, sd = 1)
  x5<-rnorm(50, mean = 0, sd = 3)
  x6<-rnorm(50, mean = 0, sd = 4)
  e<-rnorm(50, mean = 0, sd = 20)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  mSizes<-modelSizes(Post)
  expect_equal(class(mSizes[[1]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[2]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[3]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[4]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[5]]),c("gg", "ggplot","ggarrange"))
  dev.off()
})

test_that("modelSizes builds correct mSize objects (3)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-4
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  mSizes<-modelSizes(Post)
  expect_equal(class(mSizes[[1]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[2]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[3]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[4]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[5]]),c("gg", "ggplot","ggarrange"))
  dev.off()
})

test_that("modelSizes builds correct mSize objects (4)", {
  x1<-rnorm(100, mean = 0, sd = 5)
  x2<-rnorm(100, mean = 0, sd = 3)
  x3<-rnorm(100, mean = 0, sd = 7)
  x4<-rnorm(100, mean = 0, sd = 4)
  x5<-rnorm(100, mean = 0, sd = 3)
  x6<-rnorm(100, mean = 0, sd = 4)
  e<-rnorm(100, mean = 0, sd = 4)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-3
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  mSizes<-modelSizes(Post)
  expect_equal(class(mSizes[[1]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[2]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[3]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[4]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[5]]),c("gg", "ggplot","ggarrange"))
  dev.off()
})

test_that("modelSizes builds correct mSize objects (5)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  x7<-0.5*x1+rnorm(20, mean = 0, sd = 1)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6,x7)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6","x7")
  M<-6
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  mSizes<-modelSizes(Post)
  expect_equal(class(mSizes[[1]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[2]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[3]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[4]]),c("gg", "ggplot"))
  expect_equal(class(mSizes[[5]]),c("gg", "ggplot","ggarrange"))
  dev.off()
})
