test_that("BestModels builds correct BestModel (BS) objects (1)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  bestModels<-BestModels(Post,criterion=1,best=5,estimate=TRUE,showConst=TRUE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),5)
  expect_equal(ncol(bestModels[[4]]),6)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),8)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (2)", {
  x1<-rnorm(50, mean = 0, sd = 5)
  x2<-rnorm(50, mean = 0, sd = 2)
  x3<-rnorm(50, mean = 0, sd = 7)
  x4<-rnorm(50, mean = 0, sd = 1)
  x5<-rnorm(50, mean = 0, sd = 3)
  x6<-rnorm(50, mean = 0, sd = 4)
  e<-rnorm(50, mean = 0, sd = 20)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  bestModels<-BestModels(Post,criterion=2,best=5,estimate=TRUE,showConst=TRUE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),5)
  expect_equal(ncol(bestModels[[4]]),6)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),8)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (3)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-4
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  bestModels<-BestModels(Post,criterion=3,best=5,estimate=TRUE,showConst=TRUE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),5)
  expect_equal(ncol(bestModels[[4]]),6)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),8)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (4)", {
  x1<-rnorm(100, mean = 0, sd = 5)
  x2<-rnorm(100, mean = 0, sd = 3)
  x3<-rnorm(100, mean = 0, sd = 7)
  x4<-rnorm(100, mean = 0, sd = 4)
  x5<-rnorm(100, mean = 0, sd = 3)
  x6<-rnorm(100, mean = 0, sd = 4)
  e<-rnorm(100, mean = 0, sd = 4)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-3
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  bestModels<-BestModels(Post,criterion=4,best=5,estimate=TRUE,showConst=TRUE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),5)
  expect_equal(ncol(bestModels[[4]]),6)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),8)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (5)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace,dilution=1,dil.Par=0.5)
  bestModels<-BestModels(Post,criterion=1,best=5,estimate=FALSE,showConst=TRUE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),5)
  expect_equal(ncol(bestModels[[4]]),6)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),8)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (6)", {
  x1<-rnorm(50, mean = 0, sd = 5)
  x2<-rnorm(50, mean = 0, sd = 2)
  x3<-rnorm(50, mean = 0, sd = 7)
  x4<-rnorm(50, mean = 0, sd = 1)
  x5<-rnorm(50, mean = 0, sd = 3)
  x6<-rnorm(50, mean = 0, sd = 4)
  e<-rnorm(50, mean = 0, sd = 20)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace,dilution=1,dil.Par=0.5)
  bestModels<-BestModels(Post,criterion=1,best=5,estimate=TRUE,showConst=FALSE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),5)
  expect_equal(ncol(bestModels[[4]]),6)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),7)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (7)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-4
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace,dilution=1,dil.Par=0.5)
  bestModels<-BestModels(Post,criterion=1,best=4,estimate=FALSE,showConst=FALSE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),4)
  expect_equal(ncol(bestModels[[4]]),5)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),7)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (8)", {
  x1<-rnorm(100, mean = 0, sd = 5)
  x2<-rnorm(100, mean = 0, sd = 3)
  x3<-rnorm(100, mean = 0, sd = 7)
  x4<-rnorm(100, mean = 0, sd = 4)
  x5<-rnorm(100, mean = 0, sd = 3)
  x6<-rnorm(100, mean = 0, sd = 4)
  e<-rnorm(100, mean = 0, sd = 4)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-3
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace,dilution=1,dil.Par=0.5)
  bestModels<-BestModels(Post,criterion=2,best=3,estimate=FALSE,showConst=FALSE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),3)
  expect_equal(ncol(bestModels[[4]]),4)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),7)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (9)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Nar_vec<-as.matrix(c(0,1,1,1,2,2))
  Post<-Posterior(mSpace,Narrative=1,p=0.5,Nar_vec=Nar_vec)
  bestModels<-BestModels(Post,criterion=3,best=4,estimate=FALSE,showConst=TRUE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),4)
  expect_equal(ncol(bestModels[[4]]),5)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),8)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (10)", {
  x1<-rnorm(50, mean = 0, sd = 5)
  x2<-rnorm(50, mean = 0, sd = 2)
  x3<-rnorm(50, mean = 0, sd = 7)
  x4<-rnorm(50, mean = 0, sd = 1)
  x5<-rnorm(50, mean = 0, sd = 3)
  x6<-rnorm(50, mean = 0, sd = 4)
  e<-rnorm(50, mean = 0, sd = 20)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Nar_vec<-as.matrix(c(0,1,1,1,2,2))
  Post<-Posterior(mSpace,Narrative=1,p=0.5,Nar_vec=Nar_vec)
  bestModels<-BestModels(Post,criterion=4,best=4,estimate=FALSE,showConst=TRUE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),4)
  expect_equal(ncol(bestModels[[4]]),5)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),8)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (11)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-4
  mSpace<-modelSpace(data,M)
  Nar_vec<-as.matrix(c(0,1,1,1,2,2))
  Post<-Posterior(mSpace,Narrative=1,p=0.5,Nar_vec=Nar_vec)
  bestModels<-BestModels(Post,criterion=4,best=4,estimate=TRUE,showConst=TRUE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),4)
  expect_equal(ncol(bestModels[[4]]),5)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),8)
  grid::grid.newpage()
})

test_that("BestModels builds correct BestModel (BS) objects (12)", {
  x1<-rnorm(100, mean = 0, sd = 5)
  x2<-rnorm(100, mean = 0, sd = 3)
  x3<-rnorm(100, mean = 0, sd = 7)
  x4<-rnorm(100, mean = 0, sd = 4)
  x5<-rnorm(100, mean = 0, sd = 3)
  x6<-rnorm(100, mean = 0, sd = 4)
  e<-rnorm(100, mean = 0, sd = 4)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-3
  mSpace<-modelSpace(data,M)
  Nar_vec<-as.matrix(c(0,1,1,1,2,2))
  Post<-Posterior(mSpace,Narrative=1,p=0.5,Nar_vec=Nar_vec)
  bestModels<-BestModels(Post,criterion=4,best=4,estimate=TRUE,showConst=FALSE)
  expect_equal(class(bestModels[[1]]),class(bestModels[[2]]))
  expect_equal(class(bestModels[[3]]),class(bestModels[[4]]))
  expect_equal(class(bestModels[[5]]),class(bestModels[[6]]))
  expect_equal(ncol(bestModels[[3]]),4)
  expect_equal(ncol(bestModels[[4]]),5)
  expect_equal(nrow(bestModels[[3]]),7)
  expect_equal(nrow(bestModels[[4]]),7)
  grid::grid.newpage()
})
