test_that("Posterior builds correct Posterior objects (1)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-6
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.numeric(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
})

test_that("Posterior builds correct Posterior objects (2)", {
  x1<-rnorm(50, mean = 0, sd = 5)
  x2<-rnorm(50, mean = 0, sd = 2)
  x3<-rnorm(50, mean = 0, sd = 7)
  x4<-rnorm(50, mean = 0, sd = 1)
  x5<-rnorm(50, mean = 0, sd = 3)
  x6<-rnorm(50, mean = 0, sd = 4)
  e<-rnorm(50, mean = 0, sd = 20)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.null(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
})

test_that("Posterior builds correct Posterior objects (3)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-4
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.null(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
})

test_that("Posterior builds correct Posterior objects (4)", {
  x1<-rnorm(100, mean = 0, sd = 5)
  x2<-rnorm(100, mean = 0, sd = 3)
  x3<-rnorm(100, mean = 0, sd = 7)
  x4<-rnorm(100, mean = 0, sd = 4)
  x5<-rnorm(100, mean = 0, sd = 3)
  x6<-rnorm(100, mean = 0, sd = 4)
  e<-rnorm(100, mean = 0, sd = 4)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-3
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.null(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
})

test_that("Posterior with dilution builds correct Posterior objects (1)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-6
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace,dilution=1,dil.Par=0.5)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.numeric(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
})

test_that("Posterior with dilution builds correct Posterior objects (2)", {
  x1<-rnorm(50, mean = 0, sd = 5)
  x2<-rnorm(50, mean = 0, sd = 2)
  x3<-rnorm(50, mean = 0, sd = 7)
  x4<-rnorm(50, mean = 0, sd = 1)
  x5<-rnorm(50, mean = 0, sd = 3)
  x6<-rnorm(50, mean = 0, sd = 4)
  e<-rnorm(50, mean = 0, sd = 20)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace,dilution=1,dil.Par=0.5)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.null(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
})

test_that("Posterior with dilution builds correct Posterior objects (3)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-4
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace,dilution=1,dil.Par=0.5)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.null(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
})

test_that("Posterior with dilution builds correct Posterior objects (4)", {
  x1<-rnorm(100, mean = 0, sd = 5)
  x2<-rnorm(100, mean = 0, sd = 3)
  x3<-rnorm(100, mean = 0, sd = 7)
  x4<-rnorm(100, mean = 0, sd = 4)
  x5<-rnorm(100, mean = 0, sd = 3)
  x6<-rnorm(100, mean = 0, sd = 4)
  e<-rnorm(100, mean = 0, sd = 4)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-3
  mSpace<-modelSpace(data,M)
  Post<-Posterior(mSpace,dilution=1,dil.Par=0.5)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.null(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
})

test_that("Posterior with Narrative dilution builds correct Posterior objects (1)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-6
  mSpace<-modelSpace(data,M)
  Nar_vec<-as.matrix(c(0,1,1,1,2,2))
  Post<-Posterior(mSpace,Narrative=1,p=0.5,Nar_vec=Nar_vec)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.numeric(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
  expect_equal(ncol(Post[[17]]),1)
  expect_equal(nrow(Post[[17]]),mSpace[[3]])
})

test_that("Posterior with Narrative dilution builds correct Posterior objects (2)", {
  x1<-rnorm(50, mean = 0, sd = 5)
  x2<-rnorm(50, mean = 0, sd = 2)
  x3<-rnorm(50, mean = 0, sd = 7)
  x4<-rnorm(50, mean = 0, sd = 1)
  x5<-rnorm(50, mean = 0, sd = 3)
  x6<-rnorm(50, mean = 0, sd = 4)
  e<-rnorm(50, mean = 0, sd = 20)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-5
  mSpace<-modelSpace(data,M)
  Nar_vec<-as.matrix(c(0,1,1,1,2,2))
  Post<-Posterior(mSpace,Narrative=1,p=0.5,Nar_vec=Nar_vec)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.null(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
  expect_equal(ncol(Post[[17]]),1)
  expect_equal(nrow(Post[[17]]),mSpace[[3]])
})

test_that("Posterior with Narrative dilution builds correct Posterior objects (3)", {
  x1<-rnorm(20, mean = 0, sd = 1)
  x2<-rnorm(20, mean = 0, sd = 2)
  x3<-rnorm(20, mean = 0, sd = 3)
  x4<-rnorm(20, mean = 0, sd = 1)
  x5<-rnorm(20, mean = 0, sd = 2)
  x6<-rnorm(20, mean = 0, sd = 4)
  e<-rnorm(20, mean = 0, sd = 0.5)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-4
  mSpace<-modelSpace(data,M)
  Nar_vec<-as.matrix(c(0,1,1,1,2,2))
  Post<-Posterior(mSpace,Narrative=1,p=0.5,Nar_vec=Nar_vec)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.null(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
  expect_equal(ncol(Post[[17]]),1)
  expect_equal(nrow(Post[[17]]),mSpace[[3]])
})

test_that("Posterior with Narrative dilution builds correct Posterior objects (4)", {
  x1<-rnorm(100, mean = 0, sd = 5)
  x2<-rnorm(100, mean = 0, sd = 3)
  x3<-rnorm(100, mean = 0, sd = 7)
  x4<-rnorm(100, mean = 0, sd = 4)
  x5<-rnorm(100, mean = 0, sd = 3)
  x6<-rnorm(100, mean = 0, sd = 4)
  e<-rnorm(100, mean = 0, sd = 4)
  y<-2+x1+2*x2+e
  data<-cbind(y,x1,x2,x3,x4,x5,x6)
  colnames(data)<-c("y","x1","x2","x3","x4","x5","x6")
  M<-3
  mSpace<-modelSpace(data,M)
  Nar_vec<-as.matrix(c(0,1,1,1,2,2))
  Post<-Posterior(mSpace,Narrative=1,p=0.5,Nar_vec=Nar_vec)
  expect_equal(ncol(Post[[1]]),5)
  expect_equal(nrow(Post[[1]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[2]]),5)
  expect_equal(nrow(Post[[2]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[3]]),6)
  expect_equal(nrow(Post[[3]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[4]]),5)
  expect_equal(nrow(Post[[4]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[5]]),5)
  expect_equal(nrow(Post[[5]]),mSpace[[5]]+1)
  expect_equal(matrix(Post[[6]],nrow=1,ncol=mSpace[[5]]+1)[1,2:(mSpace[[5]]+1)],mSpace[[1]])
  expect_equal(Post[[7]],mSpace[[4]])
  expect_equal(Post[[8]],mSpace[[5]])
  expect_equal(Post[[9]],mSpace[[3]])
  expect_equal(ncol(Post[[10]]),4)
  expect_equal(nrow(Post[[10]]),mSpace[[5]]+1)
  expect_equal(ncol(Post[[11]]),mSpace[[4]]+4)
  expect_equal(nrow(Post[[11]]),mSpace[[3]])
  expect_equal(ncol(Post[[12]]),3*mSpace[[4]]+8)
  expect_equal(nrow(Post[[12]]),mSpace[[3]])
  expect_equal(ncol(Post[[13]]),2)
  expect_equal(nrow(Post[[13]]),mSpace[[4]]+1)
  expect_equal(ncol(Post[[14]]),4)
  expect_equal(nrow(Post[[14]]),mSpace[[3]])
  expect_equal(is.null(Post[[15]]),TRUE)
  expect_equal(nrow(Post[[16]]),mSpace[[3]])
  expect_equal(ncol(Post[[16]]),mSpace[[5]])
  expect_equal(ncol(Post[[17]]),1)
  expect_equal(nrow(Post[[17]]),mSpace[[3]])
})
